### ISSUE TITLE
Colorize code error

### ISSUE THREAD

**Issue by f-lima** [kasik96/Swift-VS-Code#2]
When you use "\"" to escape a double quote inside a string the code that follow are colorized as part of string even when the string had ended, like showed below:

![colorize error](https://cloud.githubusercontent.com/assets/14829317/18882901/88acf0c4-84b7-11e6-969b-e79c1edc626d.png)

**Comment by kasik96** [comment]
I will look into this.

**Comment by kasik96** [comment]
If you have solution for this, feel free to create Pull Request.
