### ISSUE TITLE
[vscode 1.5.3] Syntax coloring not working

### ISSUE THREAD

**Issue by ram0811** [kasik96/Swift-VS-Code#4]
![screenshot from 2016-10-09 23 32 12](https://cloud.githubusercontent.com/assets/13231841/19221581/b4f4d0f0-8e78-11e6-928b-ceba9d6f4ab8.png)

Syntax coloring is not working.

vscode 1.5.3
elementaryOS Freya derived from ubuntu 14.04

Do I need to install SourceKit?

**Comment by amitsk** [comment]
This tweak solved the issue.

cd ~/.vscode/extensions/Kasik96.swift-0.0.2/syntaxes
mv Swift.tmLanguage swift.tmLanguage
