### ISSUE TITLE
Integration with SourceKitten

### ISSUE THREAD

**Issue by piyushchauhan2011** [kasik96/Swift-VS-Code#5]
I was hoping if we could get autocomplete working with `sourcekitten` which outputs autocomplete results as json for a given query. Is it already integrated, as I installed the extension but didn't saw autocomplete, snippets works correctly though ?

**Comment by rudedogg** [comment]
For new visitors — see https://github.com/vknabel/vscode-swift-development-environment for autocomplete!

**Comment by kasik96** [comment]
Not planned, sorry.
