### ISSUE TITLE
Highlight not working

### ISSUE THREAD

**Issue by yungsem** [kasik96/Swift-VS-Code#6]
Hi, I have installed your plugin on my vs code, but when I write swift codes, the highlight doesn't work. What should I do? Many thanks.

**Comment by swarnendubiswas** [comment]
```
func makeRow(id: Any, rest: [Any]) -> String {
     return "\(id)\(rest.reduce( "", { l,r in "\(l),\(r)" }))\n"
}
```

This kills syntax highlighting.

**Comment by mgrebenets** [comment]
Here's another example:

```swift
    static let mainGroupLine = try! NSRegularExpression(pattern: "^\\s+mainGroup = ([0-9A-F]{24});$", options: [])
    static let targetsLine = try! NSRegularExpression(pattern: "^(\\s+)targets = \\($", options: [])
    static let filesLine = try! NSRegularExpression(pattern: "^(\\s+)files = \\($", options: [])
    static let childrenLine = try! NSRegularExpression(pattern: "^(\\s*)children = \\($", options: [])```
```

![image](https://user-images.githubusercontent.com/350654/43373709-d20529c4-93ee-11e8-925f-fc7c388cc2d9.png)


Highlight gets broken after 2nd line because of the regex string pattern `"^(\\s+)files = \\($"`.
More precisely it seems to get broken on the escape sequence in regex string: `\\($`:
![image](https://user-images.githubusercontent.com/350654/43373734-f157cf7a-93ee-11e8-8fa9-b6d7304d05fd.png)

**Comment by kasik96** [comment]
I will look into this.

**Comment by kasik96** [comment]
If you have solution for this, feel free to create Pull Request.
